AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  printer_custom_channel

  Sample SAM Template for printer_custom_channel

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  PrinterCustomChannelFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.9
      Environment:
          Variables:
            COMPANY_NAME: 'ACME Printing'
            COMPANY_ADDRESS: '1 Main Street'
            COMPANY_CITY: 'London'
            COMPANY_POSTCODE: 'SW1A 1AA'
            COMPANY_NUMBER: '0123 1234 321'
            PRINTNODE_API_KEY: ''
            PRINT_ENABLED: 'True'

Outputs:
  PrinterCustomChannelFunction:
    Description: "Printer Custom Channel Lambda Function ARN"
    Value: !GetAtt PrinterCustomChannelFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt PrinterCustomChannelFunctionRole.Arn
